name: Alice
on:
  issue_comment:
    types: created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: created
  push:

jobs:
  build:
    name: Alice
    runs-on: ubuntu-latest

    steps:
    - name: Notifier
      uses: GokulDas027/TelegramBridge@master
      if: always()
      with:
        chat: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        status: ${{ job.status }}
        event: ${{ github.event_name }}
        actor: ${{ github.actor }}
